### ISSUE TITLE
ReadParser parsing problem on FASTQ

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/khmer#1666] opened 2017-04-05 14:05 UTC
When running `trim-low-abund.py` on a group of fastq files with the following command:
```
trim-low-abund.py -k 21 -C 3 -M 15e9 --variable-coverage --ignore-pairs *.fq.gz
```

I received the following error message:
```
|| This is the script trim-low-abund.py in khmer.
|| You are running khmer version 2.0+1097.g3683ee3
|| You are also using screed version 0.9
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. http://dx.doi.org/10.12688/f1000research.6924.1
||   * Q Zhang, S Awad, CT Brown, https://dx.doi.org/10.7287/peerj.preprints.890v1
||
|| Please see http://khmer.readthedocs.io/en/latest/citations.html for details.


PARAMETERS:
 - kmer size =     21 		(-k)
 - n tables =      4 		(-N)
 - max tablesize = 3.8e+09 	(-x)
Estimated memory usage is 15.0 Gb (1.5e+10 bytes = 4 bytes x 3.8e+09 entries / 1 entries per byte)
--------
making countgraph
created temporary directory ./tmpp3Jknxkhmer;
use -T to change location
Traceback (most recent call last):
  File "/home/ubuntu/sourmashEnv2/bin/trim-low-abund.py", line 4, in <module>
    __import__('pkg_resources').run_script('khmer==2.0+1097.g3683ee3', 'trim-low-abund.py')
  File "/home/ubuntu/sourmashEnv2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/ubuntu/sourmashEnv2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/home/ubuntu/sourmashEnv2/lib/python2.7/site-packages/khmer-2.0+1097.g3683ee3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/trim-low-abund.py", line 488, in <module>
    main()
  File "/home/ubuntu/sourmashEnv2/lib/python2.7/site-packages/khmer-2.0+1097.g3683ee3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/trim-low-abund.py", line 363, in main
    paired_iter = broken_paired_reader(ReadParser(filename), min_length=K,
OSError: Could not open unaligned_SRR1573503qc.fq.gz for reading.
```

I ran this in a virtual environment on an AWS instance setup as follows:

```
sudo apt-get update && \
sudo apt-get -y install screen git curl gcc make g++ python-dev unzip \
        default-jre pkg-config libncurses5-dev r-base-core r-cran-gplots \
        python-matplotlib python-pip python-virtualenv sysstat fastqc \
        trimmomatic bowtie samtools blast2 wget bowtie2 openjdk-8-jre \
        hmmer ruby
```

Install sourmash
```
cd ~
python2.7 -m virtualenv sourmashEnv2
source sourmashEnv2/bin/activate
git clone https://github.com/dib-lab/sourmash.git
cd sourmash
make install
source sourmashEnv2/bin/activate
```

Install khmer from source code
```
cd ~/sourmashEvn2
pip install -U setuptools
git clone https://github.com/dib-lab/khmer.git
cd khmer
make install
```

install numpy
```
deactivate
pip install numpy 
source sourmashEnv2/bin/activate
```

When I switched to running `trim-low-abund` on a different machine with the Eel Pond `pondenv`, `trim-low-abund` ran without any errors. On that machine, khmer was installed with

```
cd ~/
python2.7 -m virtualenv pondenv
source pondenv/bin/activate
cd pondenv
pip install -U setuptools
git clone --branch v2.0 https://github.com/dib-lab/khmer.git
cd khmer
make install
```

I have also attached the output of `head` from my fastq files.

[fastq_files_head.txt](https://github.com/dib-lab/khmer/files/896472/fastq_files_head.txt)

**Comment by ctb** [comment] 2017-04-05 22:59
See #1119.

**Comment by ctb** [comment] 2017-04-16 16:29
I think #1672 fixes the notification issue. Question is, is this actually invalid FASTA/FASTQ content?

**Comment by betatim** [comment] 2017-04-21 12:03
I took the first few lines from the attached `fastq_files_head.txt` and put them into two files called `taylor.1.fq` and `taylor.2.fq`:

```
@24/1
GACATCAATGAGCCAAACCTTCAATTGATGAAATCCGTGACTAGGCAAACCACAAGGGGCCAAGCAGCCATTTTT
+ERR1346597.24 24 length=76
1:BDDBDBFF>FHBHGHFFGGGGGHGD><DGFDHIEHIGBGIGG@GGDFF1/((.8((''--(.(..?((6>@C>
@34/1
GCTGATGCTTCTGGAGCTAAGCATTTGAATATAACATTGACTAGATCAAAGTTTGAGGCTTTGGTGAATCAATTG
+ERR1346597.34 34 length=76
1=DDFFFHHHHHJJIJJJJIJJJJJJJIJIIIIIGIHJJGHIJJIJJJJJFDHGHIJJIJIJJIDGGGIIG@EED
```
and
```
@24/2
TGCTTCCAAAACTGACATAGATTACTGATTTTGGTGGCTGTGCATTAAGCCAATCCAGACAAATCCGATCTTCAGC
+ERR1346597.24 24 length=76
@@B?DDFFHHFDH@EHIJ@EEBHGGDB?CEEHIG@G??;D:BBBBHD@DHGFGEFHGCEFHGGHIFA1DA=A777?
@34/2
GCCTTGTTGTCAGAAGCCATCTCACGTTCTCCTTGCAATACTTTAATACCTACTTGGGTTTGGTTGTCAGCAGCTG
+ERR1346597.34 34 length=76
@<BFFFDFHHHHFJJIIJIGGHHIIJJJJIIJIJJJIGIJGHIJICGIEHBGFHHGJJFGGGGHHGHIJIHHGHGF
```

and ran `trim-low-abund.py -k 21 -C 3 -M 15e8 --variable-coverage --ignore-pairs taylor.*fq` which told me:

```
making countgraph
created temporary directory ./tmpwj_fm3x5khmer;
use -T to change location
Traceback (most recent call last):
  File "/home/thead/anaconda/envs/khmer-py35/bin/trim-low-abund.py", line 4, in <module>
    __import__('pkg_resources').run_script('khmer==2.0+1110.g794365b7', 'trim-low-abund.py')
  File "/home/thead/anaconda/envs/khmer-py35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/thead/anaconda/envs/khmer-py35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/home/thead/anaconda/envs/khmer-py35/lib/python3.5/site-packages/khmer-2.0+1110.g794365b7-py3.5-linux-x86_64.egg/EGG-INFO/scripts/trim-low-abund.py", line 493, in <module>
    main()
  File "/home/thead/anaconda/envs/khmer-py35/lib/python3.5/site-packages/khmer-2.0+1110.g794365b7-py3.5-linux-x86_64.egg/EGG-INFO/scripts/trim-low-abund.py", line 363, in main
    paired_iter = broken_paired_reader(ReadParser(filename), min_length=K,
OSError: File taylorreiter.1.fq contains badly formatted sequence or does not exist.
```

so I assume this isn't a valid file ... but it looks about right to my untrained eye.

(after [using all my RAM](https://twitter.com/betatim/status/855389568891330560))

**Comment by standage** [comment] 2017-04-21 18:56
This is a problem with the Fastq files. The third line of each record (the "quality defline") is not required to have any content except for a `+` at the beginning of the line. However, if it IS filled out, it must have the same content as the first line of the same record (the "sequence defline"). khmer enforces this requirement.

The Fastq format is defined ambiguously enough that it's not clear whether the *entire* first and third lines must match, or if it just applies to the first value before any whitespace. In either case, the example Fastq files provided do not comply,  and I just confirmed that the files work fine with `trim-low-abund.py` after removing the content of each quality defline.

If you have a bunch of files you want to clean up, try the following.

```bash
for file in *.fq  # or *.fastq or whatever
do
    perl -ne 's/^\+.*/+/; print' < $file > $file.better
done
```

**Comment by standage** [comment] 2017-04-28 19:36
I'm going to go ahead and close this issue. Happy to help troubleshoot data formatting issues, but it looks like khmer is working as expected.

**Closed by standage** 2017-04-28 19:36 UTC
