### ISSUE TITLE
Sporadic error occurring in threaded tests

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1099] opened 2015-06-14 12:06 UTC
``` ======================================================================
ERROR: tests.test_scripts.test_load_graph_multithread
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/t/dev/ipy/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/t/dev/khmer/tests/test_scripts.py", line 1276, in test_load_graph_multithread
    (status, out, err) = utils.runscript(script, args)
  File "/Users/t/dev/khmer/tests/khmer_tst_utils.py", line 121, in runscript
    out, err = sys.stdout.getvalue(), sys.stderr.getvalue()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/StringIO.py", line 271, in getvalue
    self.buf += ''.join(self.buflist)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf1 in position 364: ordinal not in range(128)
```

@luizirber could you take a look at it? I can't reproduce it on demand but it happens one in every ~20 test runs.

**Comment by ctb** [comment] 2015-06-14 12:11
And maybe related? Never seen this one before :)

```
======================================================================
FAIL: tests.test_scripts.test_do_partition
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/t/dev/ipy/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/t/dev/khmer/tests/test_scripts.py", line 1953, in test_do_partition
    utils.runscript(script, args, in_dir)
  File "/Users/t/dev/khmer/tests/khmer_tst_utils.py", line 129, in runscript
    assert False, (status, out, err)
AssertionError: (-1, u"running: do-partition.py in: /var/folders/y6/s1r3q87933s6gjdrtmts1npc0000gq/T/khmertest_i3DlRa\narguments [u'do-partition.py', u'-k', u'20', u'/var/folders/y6/s1r3q87933s6gjdrtmts1npc0000gq/T/khmertest_i3DlRa/out', u'/Users/t/dev/khmer/tests/test-data/random-20-a.fa']\n", u'\n|| This is the script \'do-partition.py\' in khmer.\n|| You are running khmer version test-tag+14.gba7c760.dirty\n|| You are also using screed version 0.9\n||\n|| If you use this script in a publication, please cite EACH of the following:\n||\n||   * MR Crusoe et al., 2014. http://dx.doi.org/10.6084/m9.figshare.979190\n||   * J Pell et al., http://dx.doi.org/10.1073/pnas.1121464109\n||\n|| Please see http://khmer.readthedocs.org/en/latest/citations.html for details.\n\n\nPARAMETERS:\n - kmer size =    20 \t\t(-k)\n - n tables =     4 \t\t(-N)\n - min tablesize = 1e+06 \t(-x)\n\nEstimated memory usage is 5e+05 bytes (n_tables x min_tablesize / 8)\n--------\n** WARNING: tablesize is default!  You absodefly want to increase this!\n** Please read the docs!\n\nSaving k-mer presence table to /var/folders/y6/s1r3q87933s6gjdrtmts1npc0000gq/T/khmertest_i3DlRa/out\nLoading kmers from sequences in [u\'/Users/t/dev/khmer/tests/test-data/random-20-a.fa\']\n--\nSUBSET SIZE 100000\nN THREADS 1\n--\nmaking k-mer presence table\nconsuming input /Users/t/dev/khmer/tests/test-data/random-20-a.fa\nfp rate estimated to be 0.000\n** Traverse all the things:  stop_big_traversals is false.\nenqueued 1 subset tasks\nstarting 1 threads\n---\nstarting: /var/folders/y6/s1r3q87933s6gjdrtmts1npc0000gq/T/khmertest_i3DlRa/out 0\nsaving: /var/folders/y6/s1r3q87933s6gjdrtmts1npc0000gq/T/khmertest_i3DlRa/out 0\nException in thread Thread-247:\nTraceback (most recent call last):\n  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 552, in __bootstrap_inner\n    self.run()\n  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 505, in run\n    self.__target(*self.__args, **self.__kwargs)\n  File "/Users/t/dev/khmer/tests/../scripts/do-partition.py", line 57, in worker\n    except queue.Empty:\nAttributeError: Queue instance has no attribute \'Empty\'\n\nTraceback (most recent call last):\n  File "/Users/t/dev/khmer/tests/khmer_tst_utils.py", line 111, in runscript\n    status = _runscript(scriptname, sandbox=sandbox)\n  File "/Users/t/dev/khmer/tests/khmer_tst_utils.py", line 74, in _runscript\n    exec(compile(open(scriptfile).read(), scriptfile, \'exec\'), ns)\n  File "/Users/t/dev/khmer/tests/../scripts/do-partition.py", line 235, in <module>\n    main()\n  File "/Users/t/dev/khmer/tests/../scripts/do-partition.py", line 194, in main\n    assert threading.active_count() == args.threads + 1\nAssertionError\n')
-------------------- >> begin captured stdout << ---------------------
running: do-partition.py in: /var/folders/y6/s1r3q87933s6gjdrtmts1npc0000gq/T/khmertest_i3DlRa
arguments [u'do-partition.py', u'-k', u'20', u'/var/folders/y6/s1r3q87933s6gjdrtmts1npc0000gq/T/khmertest_i3DlRa/out', u'/Users/t/dev/khmer/tests/test-data/random-20-a.fa']


|| This is the script 'do-partition.py' in khmer.
|| You are running khmer version test-tag+14.gba7c760.dirty
|| You are also using screed version 0.9
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2014. http://dx.doi.org/10.6084/m9.figshare.979190
||   * J Pell et al., http://dx.doi.org/10.1073/pnas.1121464109
||
|| Please see http://khmer.readthedocs.org/en/latest/citations.html for details.


PARAMETERS:
 - kmer size =    20            (-k)
 - n tables =     4             (-N)
 - min tablesize = 1e+06        (-x)

Estimated memory usage is 5e+05 bytes (n_tables x min_tablesize / 8)
--------
** WARNING: tablesize is default!  You absodefly want to increase this!
** Please read the docs!

Saving k-mer presence table to /var/folders/y6/s1r3q87933s6gjdrtmts1npc0000gq/T/khmertest_i3DlRa/out
Loading kmers from sequences in [u'/Users/t/dev/khmer/tests/test-data/random-20-a.fa']
--
SUBSET SIZE 100000
N THREADS 1
--
making k-mer presence table
consuming input /Users/t/dev/khmer/tests/test-data/random-20-a.fa
fp rate estimated to be 0.000
** Traverse all the things:  stop_big_traversals is false.
enqueued 1 subset tasks
starting 1 threads
---
starting: /var/folders/y6/s1r3q87933s6gjdrtmts1npc0000gq/T/khmertest_i3DlRa/out 0
saving: /var/folders/y6/s1r3q87933s6gjdrtmts1npc0000gq/T/khmertest_i3DlRa/out 0
Exception in thread Thread-247:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/t/dev/khmer/tests/../scripts/do-partition.py", line 57, in worker
    except queue.Empty:
AttributeError: Queue instance has no attribute 'Empty'

Traceback (most recent call last):
  File "/Users/t/dev/khmer/tests/khmer_tst_utils.py", line 111, in runscript
    status = _runscript(scriptname, sandbox=sandbox)
  File "/Users/t/dev/khmer/tests/khmer_tst_utils.py", line 74, in _runscript
    exec(compile(open(scriptfile).read(), scriptfile, 'exec'), ns)
  File "/Users/t/dev/khmer/tests/../scripts/do-partition.py", line 235, in <module>
    main()
  File "/Users/t/dev/khmer/tests/../scripts/do-partition.py", line 194, in main
    assert threading.active_count() == args.threads + 1
AssertionError


--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 456 tests in 25.445s

FAILED (failures=1)
make: *** [test] Error 1
```

**Comment by mr-c** [comment] 2015-07-30 18:13
Ping @luizirber  :-)

**Comment by luizirber** [comment] 2015-07-30 18:40
I couldn't reproduce them yet, I'll try it on OSX when I get access to it...

On Thu, Jul 30, 2015 at 2:13 PM, Michael R. Crusoe <notifications@github.com

**Comment by mr-c** [comment] 2015-07-30 22:27
Do you want an account on the Dev Imac?

On Thu, Jul 30, 2015 at 11:40 AM Luiz Irber <notifications@github.com>
wrote:

> I couldn't reproduce them yet, I'll try it on OSX when I get access to
> it...
>
> On Thu, Jul 30, 2015 at 2:13 PM, Michael R. Crusoe <
> notifications@github.com
> > wrote:
>
> > Ping @luizirber <https://github.com/luizirber> :-)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dib-lab/khmer/issues/1099#issuecomment-126422183>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dib-lab/khmer/issues/1099#issuecomment-126428287>.
>
-- 
Michael R. Crusoe: Programmer & Bioinformatician crusoe@ucdavis.edu
The lab for Data Intensive Biology; University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe

**Comment by standage** [comment] 2017-02-22 19:32
Have you seen this at all recently @ctb? I certainly never have.

**Comment by ctb** [comment] 2017-02-22 19:35
not any more

On Wed, Feb 22, 2017 at 11:32:56AM -0800, Daniel Standage wrote:
> Have you seen this at all recently @ctb? I certainly never have.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/khmer/issues/1099#issuecomment-281776659
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by standage** [comment] 2017-02-22 19:36
Closing for now, then.

**Closed by standage** 2017-02-22 19:36 UTC
