### ISSUE TITLE
khmer 1.4.1 is failing to install on Ubuntu 14.04

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1280] opened 2015-08-27 12:38 UTC
I get:
```
% python setup.py install
Traceback (most recent call last):
  File "setup.py", line 157, in <module>
    if "-rc" in versioneer.get_version():
TypeError: argument of type 'NoneType' is not iterable
```

when running the commands in http://khmer-protocols.readthedocs.org/en/ctb/mrnaseq/1-quality.html:

```
cd ~/
python2.7 -m virtualenv work
source work/bin/activate
pip install -U setuptools
git clone --branch v1.4.1 https://github.com/dib-lab/khmer.git
cd khmer
make install
```

Odd, because I could have sworn they worked before. What am I missing? :)

**Comment by mr-c** [comment] 2015-08-27 21:03
I can reproduce this.

However `pip install khmer` or `pip install khmer==1.4.1` works for me

**Comment by ctb** [comment] 2015-08-27 21:07
Those are not options for certain uses - in particular, when we need sandbox/.  Isn't

     python setup.py install

tested in the release process?

**Comment by mr-c** [comment] 2015-08-27 21:19
It may be due to checking out from a branch instead of the tag. Honestly
you are better off downloading the tarball from the release page or pypi
(both include sandbox).

On Thu, Aug 27, 2015 at 2:07 PM C. Titus Brown <notifications@github.com>
wrote:

> Those are not options for certain uses - in particular, when we need
> sandbox/. Isn't
>
>  python setup.py install
>
> tested in the release process?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dib-lab/khmer/issues/1280#issuecomment-135555176>.
>
-- 
Michael R. Crusoe: Programmer & Bioinformatician crusoe@ucdavis.edu
The lab for Data Intensive Biology; University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe

**Comment by mr-c** [comment] 2015-08-27 21:20
We only test installing from artifacts like a tarball or PyPI in the
release test.

On Thu, Aug 27, 2015 at 2:19 PM Michael Crusoe <michael.crusoe@gmail.com>
wrote:

> It may be due to checking out from a branch instead of the tag. Honestly
> you are better off downloading the tarball from the release page or pypi
> (both include sandbox).
>
> On Thu, Aug 27, 2015 at 2:07 PM C. Titus Brown <notifications@github.com>
> wrote:
>
>> Those are not options for certain uses - in particular, when we need
>> sandbox/. Isn't
>>
>>  python setup.py install
>>
>> tested in the release process?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dib-lab/khmer/issues/1280#issuecomment-135555176>.
>>
> --
> Michael R. Crusoe: Programmer & Bioinformatician crusoe@ucdavis.edu
> The lab for Data Intensive Biology; University of California, Davis
> https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe
>
-- 
Michael R. Crusoe: Programmer & Bioinformatician crusoe@ucdavis.edu
The lab for Data Intensive Biology; University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe

**Comment by ctb** [comment] 2015-09-07 21:59
Sorry, why was this closed?

**Comment by mr-c** [comment] 2015-09-08 03:30
Sorry, I thought the work around was acceptable. Could be different due to 1.4.1 being created off a branch instead of master like we normally due. There is already an issue open to track upgrading to the latest versioneer release which may also fix the problem in the future.

**Comment by ctb** [comment] 2015-09-08 12:40
OK, may be fixed by #1272.

**Comment by ctb** [comment] 2015-09-08 13:06
Also,

     git checkout v1.4.1
     make

fails with the same problem.

**Comment by mr-c** [comment] 2015-09-08 16:44
Oh, the branch comment was about how the 1.4.1 release was made, not your checkout procedure. If 1.4 doesn't fail then that would be diagnostic.

**Comment by standage** [comment] 2016-06-28 04:22
No issues now on Ubuntu 14.04 with branch v1.4.1 or with latest master, closing.

**Closed by standage** 2016-06-28 04:22 UTC
