### ISSUE TITLE
screed test failure

### ISSUE THREAD

**Issue by wwood** [dib-lab/khmer#1384] opened 2016-06-14 06:07 UTC
Hi,

I'm attempting to package screed and khmer for GNU Guix. I came across this error when running the screed tests. On first glance, it seems the test is streaming in gzip data when the reader explicitly disallows it. So is this an expected failure? All the other tests pass.

This is with the 0.9 code from pypi.

```
======================================================================
ERROR: screed.tests.test_streaming.test_stream_fa_gz
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gnu/store/4addsbkghgygd9l857zk4issfjmjq9ya-python-nose-1.3.7/lib/python3.4/site-packages/nose-1.3.7-py3.4.egg/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/nix-build-python-screed-0.9.drv-5/screed-0.9/screed/tests/test_streaming.py", line 72, in test_stream_fa_gz
    streamer(utils.get_test_data('test.fa.gz'))
  File "/tmp/nix-build-python-screed-0.9.drv-5/screed-0.9/screed/tests/test_streaming.py", line 59, in streamer
    raise exception[0]
  File "/tmp/nix-build-python-screed-0.9.drv-5/screed-0.9/screed/tests/test_streaming.py", line 24, in streamer_reader
    for read in screed.open(ifilename):
  File "/tmp/nix-build-python-screed-0.9.drv-5/screed-0.9/screed/openscreed.py", line 48, in __init__
    self.iter_fn = self.open_reader(filename, *args, **kwargs)
  File "/tmp/nix-build-python-screed-0.9.drv-5/screed-0.9/screed/openscreed.py", line 80, in open_reader
    first")
ValueError: gziped data not streamable, pipe through zcat                                 first

======================================================================
ERROR: screed.tests.test_streaming.test_stream_fq_gz
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gnu/store/4addsbkghgygd9l857zk4issfjmjq9ya-python-nose-1.3.7/lib/python3.4/site-packages/nose-1.3.7-py3.4.egg/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/nix-build-python-screed-0.9.drv-5/screed-0.9/screed/tests/test_streaming.py", line 85, in test_stream_fq_gz
    streamer(utils.get_test_data('test.fastq.gz'))
  File "/tmp/nix-build-python-screed-0.9.drv-5/screed-0.9/screed/tests/test_streaming.py", line 59, in streamer
    raise exception[0]
  File "/tmp/nix-build-python-screed-0.9.drv-5/screed-0.9/screed/tests/test_streaming.py", line 24, in streamer_reader
    for read in screed.open(ifilename):
  File "/tmp/nix-build-python-screed-0.9.drv-5/screed-0.9/screed/openscreed.py", line 48, in __init__
    self.iter_fn = self.open_reader(filename, *args, **kwargs)
  File "/tmp/nix-build-python-screed-0.9.drv-5/screed-0.9/screed/openscreed.py", line 80, in open_reader
    first")
ValueError: gziped data not streamable, pipe through zcat                                 first

----------------------------------------------------------------------
```

Thanks,
ben

**Comment by wwood** [comment] 2016-06-14 06:34
And on second glance I see that each of those two has `@attr('known_failing')` above it. So then all tests pass running `nosetests --attr '!known_failing'`. However, this is not what `python setup.py test` does. Perhaps this an issue or not, I'll let you maintainers decide. Thanks.

**Comment by ctb** [comment] 2016-06-14 12:10
thank you for reporting this!

**Comment by ctb** [comment] 2016-12-19 22:47
@luizirber this seems to have been fixed along the way - at least, `python setup.py test` now works. Can you confirm & shall I close as fixed?

**Comment by standage** [comment] 2016-12-19 22:49
The issue is with `python -m screed.tests` after a pip install. Still pending.

**Comment by standage** [comment] 2016-12-20 01:02
Fixed in https://github.com/dib-lab/screed/pull/61.

**Closed by standage** 2016-12-20 01:02 UTC
Labels: screed
